### ISSUE TITLE
AWS Image Upload

### ISSUE THREAD

**Issue by caroline171** [agilord/aws_client#1]
Is there any means now to use the library now for uploading AWS photos to an S3 storage bucket ?

**Comment by isoos** [comment]
Sorry that hasn't been implemented in this library yet.

**Comment by Schwusch** [comment]
@caroline171 Have you tried the generated package?
https://pub.dev/packages/aws_s3_api

**Comment by Schwusch** [comment]
I'll close this, assuming the problem is solved
