### ISSUE TITLE
" method, newHttpClient() is not found" ERROR !!!

### ISSUE THREAD

**Issue by HotCodeworker** [agilord/aws_client#11]
I tried to build a sample example as main.dart after referring below link on andoirdstudio.
https://pub.dev/packages/aws_client, [https://pub.dev/packages/aws_client](url)

`
import 'package:aws_client/aws_client.dart';
import 'package:http_client/console.dart';

main() async {
  var httpClient = newHttpClient();
  var credentials = new Credentials(accessKey: 'MY_ACCESS_KEY', secretKey: 'MY_SECRET_KEY');
  var aws = new Aws(credentials: credentials, httpClient: httpClient);
  var queue = aws.sqs.queue('https://my-queue-url/number/queue-name');
  await queue.sendMessage('Hello from Dart client!');
  httpClient.close();
}

`

But I git the following error at logs:

` "method, newHttpClient() is not found" `

Please, let me know how to solve this error.
Thanks in advance.

**Comment by isoos** [comment]
Try `new ConsoleClient()`.
`newHttpClient` is just a placeholder to decide how to configure your client.

**Comment by Schwusch** [comment]
@isoos I guess this has been inactive for a while, time to close?

**Comment by isoos** [comment]
Yeah, especially as the generated package depend on `package:http`.
