### ISSUE TITLE
Improve enum parameters

### ISSUE THREAD

**Issue by Schwusch** [agilord/aws_client#115]
I would like better type safety and user ergonomics for enumerated parameters.

A suggestion would be enums with extensions:
```dart
enum AttributeAction {
  ADD,
  PUT,
  DELETE
}

extension on AttributeAction {
  String get name {
    switch (this) {
      case AttributeAction.ADD:
        return 'ADD';
      case AttributeAction.PUT:
        return 'PUT';
      case AttributeAction.DELETE:
        return 'DELETE';
    }
    throw Exception('This will never throw');
  }
}
```

This would be received as such:
```dart 
foo(AttributeAction action) {
  bar(action.name)
}
```

And the call `foo()` would be:
```dart
foo(AttributeAction.ADD) ;
```
@isoos, what do you think?

**Comment by isoos** [comment]
I'd like to see an API call where the enum would be used in a meaningful way. If the client uses the enum value as part of an input request, then the current generated String references seem to be just as good. If they are used in processing an output, then this is not much different from using `switch (value) { case AttributeAction.add: break; }` which works nicely if `add` is `String`.

Unless we have a good reason to make these top-level enums, I don't think we need to increase the complexity of the codegen and the length of the generate code.

**Comment by Schwusch** [comment]
How will the users of our packages know about the current generated String references? Is it implied somewhere that they exist?

I'm just thinking from a noobie perspective, if I'm using a service for the first time. I'd like the enum from a developer velocity point of view.

**Comment by isoos** [comment]
> How will the users of our packages know about the current generated String references?

That's a good point!

Maybe we could start with enum-like classes:

```dart
class AttributeAction {
  final String name;
  const AttributeAction(this.name);

  static const add = AttributeAction('ADD');
  static const put = AttributeAction('PUT');
  static const delete = AttributeAction('DELETE');
  static final _values = <AttributeAction>[add, put, delete,];

  static AttributeAction parse(String value) {
    if (value == null) return value;
    return _values.firstWhere((v) => v.name == value);
  }
}
```

**Comment by Schwusch** [comment]
I guess a class works too, if the constructor is private, to not confuse users. A public constructor would imply  that you should instantiate it manually.

The backside of the class would be that the documentation might confuse users. I've seen some documentation refer to `AttributeAction.ADD` in this case.

**Comment by isoos** [comment]
>  if the constructor is private, to not confuse users. A public constructor would imply that you should instantiate it manually.

I don't think that a public constructor is too bad. The API may be extended by AWS and new values can be plugged in easily by the users of the library.

> I've seen some documentation refer to AttributeAction.ADD in this case.

I'd rather have the generated code Dart-ish, and try to convert the documentation to use `AttributeAction.add`.

**Comment by Schwusch** [comment]
I dove head first into this, and the class approach is seriously complicated to serialize/deserialize.
We have to create a `JsonConverter` for every enum/class and annotate that field with the converter.

If we chose enums, I think there is support in `json_serializable`: https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonValue-class.html
I'm just trying to figure out how to use it.

**Comment by Schwusch** [comment]
It should be said, the `JsonConverter` issue is when the enum is inside another class.
In `dynamodb-2012-08-10.dart` the `AttributeDefinition` class has a member `attributeType` of type `ScalarAttributeType`, which is a String enum.

**Comment by isoos** [comment]
A sidenote: `JsonKey` has `toJson` and `fromJson` method, we could use them as a single function call.

Another thing to consider: if this seems to be too complex for now, we should probably defer it to a later release, as it provides more value to concentrate on the missing protocols. (It may be a breaking one for the generated packages, but that is handled by a major version changes).

**Comment by Schwusch** [comment]
I tried the `JsonKey.toJson` field, without success. I don't know if it's a bug in `json_serializer` or if it's only to be used as an override or something. 

I'm going to try the enum way real quick.

**Comment by Schwusch** [comment]
This falls apart because xml-based schemas doesn't use `json_serializer`...

**Comment by isoos** [comment]
> This falls apart because xml-based protocols doesn't use json_serializer...

Yeah, those would need to be implemented separately... :(

**Comment by Schwusch** [comment]
This is implemented in https://github.com/agilord/aws_client/pull/116
