### ISSUE TITLE
snake_case conversions

### ISSUE THREAD

**Issue by isoos** [agilord/aws_client#122]
I've noticed that a lot of the enum values have `snake_case` format, which we may transform to `lowerCamelCase` (or whatever the name for it is). For some it works fine, but for e.g. `usEast1` it is debatable if it is better than `us_east_1`). @Schwusch wdyt?

**Comment by Schwusch** [comment]
I don't really have an opinion on the matter, as long as they are understandable and functional.
On one hand Effective Dart says [camel case is preferred for constant names](https://dart.dev/guides/language/effective-dart/style#prefer-using-lowercamelcase-for-constant-names), on the other it says further down:

> You may use SCREAMING_CAPS for consistency with existing code, as in the following cases:
> When generating Dart code that’s parallel to Java code — for example, in enumerated types generated from protobufs.

Not sure what's best here
¯\\_(ツ)\_/¯
