### ISSUE TITLE
main library for each generated package

### ISSUE THREAD

**Issue by isoos** [agilord/aws_client#129]
Right now we get a warning when publishing to pub:
```
* The name of "lib/route53-2013-04-01.dart", "route53-2013-04-01", should match the name of the package, "aws_route53_api".
This helps users know what library to import.
```

**Comment by Schwusch** [comment]
Tricky problem.
We could generate a `aws_route53_api.dart` looking something like this:

```dart
export 'package: aws_route53_api/route53-2013-04-01.dart';
```
But it cannot export different versions because they have the same class name, e.g. DynamoDB.
```dart
export 'package:aws_dynamodb_api/dynamodb-2012-08-10.dart';
export 'package:aws_dynamodb_api/dynamodb-2011-12-05.dart';
```

Is the warning going to give us negative points or have any other consequences?

**Comment by isoos** [comment]
> Is the warning going to give us negative points or have any other consequences?

Probably no consequences, so we could ignore it for now...

**Comment by Schwusch** [comment]
We could encourage to use the latest version, and only export the one with the latest date. 
The older versions will still be available anyway.
wdyt?

**Comment by isoos** [comment]
That could work, but then we'd need to track if there is a new version, and do a major version increase, as it would be potentially breaking for people that included the generic library.

**Comment by Schwusch** [comment]
Well, that settles it for me. That sounds way to complex...

**Comment by Schwusch** [comment]
I'll close this for now, it can be reopened if there is negative consequences in the future.
