### ISSUE TITLE
Generate tests

### ISSUE THREAD

**Issue by Schwusch** [agilord/aws_client#138]
We should be able to generate protocol test cases, much like [aws-sdk-go](https://github.com/aws/aws-sdk-go-v2/tree/master/models/protocol_tests). 
It would help development a lot to know if the implementations are correct.

**Comment by isoos** [comment]
Nice idea!

**Comment by Schwusch** [comment]
The Go SDK generate [smoke tests for the APIs as well](https://github.com/aws/aws-sdk-go-v2/blob/master/private/model/api/smoke.go), I am investigating if it is feasible in our case as well, using their test definitions.

**Comment by Schwusch** [comment]
I see now that [aws-sdk-has the same protocol tests,](https://github.com/aws/aws-sdk-js/tree/master/test/fixtures/protocol) might be good to know

**Comment by Schwusch** [comment]
@xvrh solved this for us :D
