### ISSUE TITLE
http library version upgrade

### ISSUE THREAD

**Issue by michael-golfi** [agilord/aws_client#139]
Hi!

Thanks for the great work! I'm looking to use the generated APIs here and I was wondering if it would be possible to upgrade the version of http. I'm getting a version incompatibility error when running pub upgrade.

Thanks

**Comment by isoos** [comment]
@michael-golfi: apologies, I haven't noticed that we've pinned the version. I'll update and release a new one soon.

**Comment by isoos** [comment]
Released a new version, please reopen if this is still an issue for some reason.
