### ISSUE TITLE
Latest versions on pub

### ISSUE THREAD

**Issue by michael-golfi** [agilord/aws_client#140]
Hi!

Thanks for the great work! I'm looking to use the generated APIs here and I was wondering if it would be possible to publish the latest library version on pub. I generated the API for the aws_logs_api and it requires the latest version of the aws_shared_api to be published with the JSON protocol's send function available.

Thanks

**Comment by isoos** [comment]
@michael-golfi: By the "latest library version", you mean the shared lib? That was just published, let me know if you need something else. (And thanks for trying out!)

**Comment by michael-golfi** [comment]
Yes, the shared lib :).

Thanks!
