### ISSUE TITLE
type error in underlying sigv4 client

### ISSUE THREAD

**Issue by michael-golfi** [agilord/aws_client#142]
Hi again!

I'm trying to generate the AWS logs api for Cloudwatch and I'm getting the following error. I think it's due to the version of sigv4 being used.

```dart
// Line client.dart:117-118
headers[_x_amz_decoded_content_length] = utf8.encode(body).length;
headers['Content-Length'] = utf8.encode(body).length;
```

```bash
#0      _LinkedHashMapMixin.[]= (dart:collection-patch/compact_hash.dart)
#1      Sigv4Client.signedHeaders (package:sigv4/src/client.dart:117:14)
#2      Sigv4Client.request (package:sigv4/src/client.dart:187:5)
#3      JsonProtocol.sendRequest (package:shared_aws_api/src/protocol/json.dart:85:33)
#4      JsonProtocol.send (package:shared_aws_api/src/protocol/json.dart:55:22)
#5      CloudWatchLogs.putLogEvents (package:aws_logs_api/logs-2014-03-28.dart:2224:42)
```

The problem seems to be fixed in sigv4: 4.0.0. I used a dependency override to verify. Although the interface to the client changed and it expects a body of type string, not Map:

```bash
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: type '_InternalLinkedHashMap<String, Object>' is not a subtype of type 'String'
#0      JsonProtocol.sendRequest (package:shared_aws_api/src/protocol/json.dart:90:17)
#1      JsonProtocol.send (package:shared_aws_api/src/protocol/json.dart:55:22)
#2      CloudWatchLogs.putLogEvents (package:aws_logs_api/logs-2014-03-28.dart:2224:42)
```

I updated json.dart:84-94 to the following and it seemed to fix the problem:

```dart
      case 'POST':
        final jsonBody = json.encode(body);
        final rq = _sigv4client.request(
          url,
          method: method.toUpperCase(),
          query: queryParams,
          headers: headers,
          body: jsonBody,
        );
        rs = await _client.post(rq.url, headers: rq.headers, body: rq.body);
        break;
```

**Comment by Schwusch** [comment]
It's good to hear that you managed to solve it!
If you have the time, a PR would be most appreciated :)

**Comment by michael-golfi** [comment]
@Schwusch yes, of course :)

@isoos - I had another issue I was trying to figure out before submitting something. I'm getting unauthorized exceptions with the correct key ID and secret access key.

**Comment by isoos** [comment]
@michael-golfi: should we wait for that (while you debug or report it) before I release the shared library with the sigv4 upgrade?

**Comment by michael-golfi** [comment]
I can continue debugging anyways. I need to check if the body is getting encoded properly. The error says that the signature does not match the one the server calculated.
