### ISSUE TITLE
[BUG] Error When Flattening MessageAttributeValue and MessageSystemAttributeValue

### ISSUE THREAD

**Issue by lucasdina** [agilord/aws_client#144]
When sending an SQS message, the library attempts to flatten the extra parameters from sendMessage() at sqs-2012-11-15.dart:1681 in the auto generated package. The optional parameters are for the messageAttributes (Map<String, MessageAttribute>) and messageSystemAttributes (Map<String, MessageSystemAttribute>). Somewhere down the line, send() gets called at query.dart:42 in the shared auto generated package which calls _buildRequest() > flatQueryParams() > _flatten() all in the same file. _flatten checks for the type to flatten it for the request but fails because there is no case to handle MessageAttribute or MessageSystemAttribute. I would fix and submit another PR but I don't really have the time. Here is the error:

 ```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Invalid argument(s): Unknown type at "MessageAttributes.entry.1.value": MessageAttributeValue (Instance of 'MessageAttributeValue')
#0      _flatten (package:shared_aws_api/src/protocol/query.dart:140:3)
#1      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:146:12)
#2      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:139:32)
#3      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:139:32)
#4      MapMixin.addEntries (dart:collection/maps.dart:172:23)
#5      new Map.fromEntries (dart:core/map.dart:187:17)
#6      flatQueryParams (package:shared_aws_api/src/protocol/query.dart:89:14)
#7      QueryProtocol._buildRequest (package:shared_aws_api/src/protocol/query.dart:74:26)
#8      QueryProtocol.send (package:shared_aws_api/src/protocol/query.dart:49:16)
#9      SQS.sendMessage (package:aws_sqs_api/sqs-2012-11-05.dart:1705:37)
```

EDIT: Here is my code causing the error:
```
    sqs.sendMessage(
        messageBody: unsentEntries[i].toJson().toString(),
        queueUrl: sqsUrl,
        messageGroupId: unsentEntries[i].company.shortName.replaceAll(' ', ''),
        messageDeduplicationId: utils.getUuid(),
        messageAttributes: <String, MessageAttributeValue>{
          'companyId': new MessageAttributeValue(dataType:'string', stringValue: unsentEntries[i].company.id)
        });
```

**Comment by lucasdina** [comment]
I previously lied when I said I didn't have time. Working on a PR right now XD

**Comment by isoos** [comment]
This is a difficult problem. The data type SQS is using is rich:
https://github.com/agilord/aws_client/blob/master/generated/aws_sqs_api/lib/sqs-2012-11-05.dart#L2470-L2522

However, we only have the basic algorithm for flattening the arguments:
https://github.com/agilord/aws_client/blob/master/shared_aws_api/lib/src/protocol/query.dart#L92-L142

@Schwusch: any idea how we should approach this?

@lucasdina: do you happen to know the wire format of your request? (e.g. what should be the body format if you specify the attributes?)

**Comment by lucasdina** [comment]
Here's what the body should look like: 
```
Action=SendMessage&MessageAttribute.1.Name=testAttribute&MessageAttribute.1.Type=String&MessageAttribute.1.Value=ab0c6c4e50ce4bcd8709eefdbd533a35&MessageBody=%7B%22test%22%3A+%22cool%22%7D&MessageDeduplicationId=8c1056b07c8f11eaf1cde9f670f7ada1&MessageGroupId=testGroup1&QueueUrl={mySQSUrl}&Version=2012-11-05
```
MessageAttribute and MessageSystemAttribute (now shown) are both maps and have the same format with the exception of the object name. In my PR I pretty much hard coded the MessageAttribute prefixes.

**Comment by isoos** [comment]
@lucasdina: Thanks!

That's even more interesting: we'd need to map `DataType` to `Type`, and `StringValue` to `Value`. I don't see anything in the JSON API spec that would help us to do that automatically.

@Schwusch: what if we introduce an interface that the shared API can interpret, and make a special case in the codegen for this `MessageAttribute`? That seems to me the least bad resolution of this so far...

**Comment by Schwusch** [comment]
Sorry, I don't have much time to dig in to this right now, but I would look at the Javascript implementation for reference. That would probably clarify things.

**Comment by lucasdina** [comment]
@isoos I apologize, I accidently sent the wrong body. That was the one I had in my notes for some reason. This one is the one what SQS accepts:
```
Action=SendMessage&MessageAttribute.1.Name=testattrib&MessageAttribute.1.Value.DataType=String&MessageAttribute.1.Value.StringValue=test&MessageBody=%7B%22test%22%3A+%22cool%22%7D&MessageDeduplicationId=4a7f57c07cf611eaf1cde9f670f7ada1&MessageGroupId=AgriPayFarms&QueueUrl={sqsUrl}&Version=2012-11-05
```
It requires that extra '.Value' prefix.

**Comment by isoos** [comment]
Ah, okay, the updated body seems to be better: we still need to generate a toJson() method for it, but it could be much more generic.

**Comment by Schwusch** [comment]
I did some digging.
The JS SDK uses a [`QueryParamSerializer`](https://github.com/aws/aws-sdk-js/blob/master/lib/protocol/query.js#L20) in the query protocol.
It in its turn uses metadata from the spec to [serialize](https://github.com/aws/aws-sdk-js/blob/59512e1eba4e30b2d91fbde21833118eaa53051c/lib/query/query_param_serializer.js#L18 ) the data.
The spec gives that the [`locationName`](https://github.com/aws/aws-sdk-js/blob/master/apis/sqs-2012-11-05.normal.json#L969) should be `Value`.
Maybe it gives some pointers.

**Comment by Schwusch** [comment]
@isoos The current flattening algorithm looks alright, the arguments just need to be json, as you said.
I guess the `query` protocol has to be added in [Api.generateToJson](https://github.com/agilord/aws_client/blob/master/generator/lib/model/api.dart#L55) and the arguments has to be serialized [here](https://github.com/agilord/aws_client/blob/master/generator/lib/builders/protocols/query_builder.dart#L32) and [here](https://github.com/agilord/aws_client/blob/master/generator/lib/builders/protocols/query_builder.dart#L35). I think that's a good start atleast.

**Comment by isoos** [comment]
Looks like we are not alone in this issue: https://github.com/pplu/aws-sdk-perl/issues/267

Btw. I've just noticed, that the expected format not only flattens the Map of Map, but also removes the plural from the attribute name. Which is a bit tricky, but I guess we should do it too...

**Comment by isoos** [comment]
I think this issue cannot be solved with the current `[ShapeClass].toJson()` output and generic flatten method. We'll need to generate e.g. an inlined `toFlatMap(String prefix)` that will provide the map based on the shape's config, and "inlined" values will (should) know what to do.

**Comment by Dvoikin** [comment]
@Schwusch this issue is still actual for our project. When it will be fixed?

**Comment by Schwusch** [comment]
@Dvoikin I don't have time to work on it in the near future, but send us a pull request and we'll have a look at it! 
It seems @isoos gave it [a shot](https://github.com/agilord/aws_client/commit/307d7f4ad425a746ae994cffb426d7239aeed206), that commit can perhaps give some pointers.

**Comment by Schwusch** [comment]
This should be fixed in [version 0.1.1](https://pub.dev/packages/aws_sqs_api/versions/0.1.1). @Dvoikin @lucasdina Can you verify?

**Comment by Schwusch** [comment]
I'll close this for now, the activity indicates that this issue is either solved or not a problem anymore.

**Comment by Dvoikin** [comment]
@Schwusch sorry for the delay. We checked your updates and, unfortunately, they do not work for AWS SNS. We are trying to configure the service for sending SMS. Below is the code:
```dart
var credentials = AwsClientCredentials(
        accessKey: ***,
        secretKey: ***);
sns = SNS(region: 'eu-west-1', credentials: credentials); // Error occurred here
```
We see the next error message: **Exception has occurred.
_CastError (type '_ImmutableMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>' in type cast)**

In case when we put shapes = null initialization instead of ```
shapes = shapesJson
            .map((key, value) => MapEntry(key, _s.Shape.fromJson(value)));
``` 
in **SNS class**, it works, but, of course, we face issues later bc shapes are null. 

Hopefully, it will help you. But it still doesn't work for us.

**Comment by Schwusch** [comment]
Thanks for replying!
I just tried and adding SNS 0.1.1 to another project I'm working on, just initializing it like so:
```dart
final sns = SNS(region: 'eu-west-1', credentials: AwsClientCredentials(accessKey: '', secretKey: ''));
```
It compiled and did not throw any runtime errors. I suspect it will be work if you run `pub upgrade` in your project, getting the latest `shared_aws_api`. Tell me if that doesn't work.
