### ISSUE TITLE
Make AwsClientCredentials constructor argument optional

### ISSUE THREAD

**Issue by Schwusch** [agilord/aws_client#160]
In the JS SDK the usage is more ergonomic:
```javascript
const secretsManager = new AWS.SecretsManager({ 'region':  'eu-west-1' });
...
```
This step:
```dart
final environment = Platform.environment;
final credentials = AwsClientCredentials(
  accessKey: environment['AWS_ACCESS_KEY_ID'],
  secretKey: environment['AWS_SECRET_ACCESS_KEY'],
  sessionToken: environment['AWS_SESSION_TOKEN'],
);
// final secretsManager = SecretsManager(region: region, credentials: credentials);
```
We should be able to do that step in the protocol factory constructor if credentials are null.
That change would make onboarding new users smoother.

**Comment by isoos** [comment]
sgtm

**Comment by Schwusch** [comment]
The pattern for doing so in other AWS SDKs is described here, just disregard the Java specific stuff:
https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html

**Comment by isoos** [comment]
The only issue I have with the auto-detection is that right now the library is generic, it can be accessed on all the platforms. If we do auto-detection, it will to an extent, be hard-wired to use `dart:io`, making the libraries incompatible with JS apps.

Maybe a few indirection here and there would solve that... not sure yet what's the best decision here.

**Comment by Schwusch** [comment]
We do conditional imports with stubs on the web, as demonstrated in this article: https://medium.com/@rody.davis.jr/how-to-build-a-native-cross-platform-project-with-flutter-372b9e4b504f

**Comment by isoos** [comment]
Yeah, as long as `package:http` is using it, we can use it too...
