### ISSUE TITLE
Write a DocumentClient for DynamoDB

### ISSUE THREAD

**Issue by Schwusch** [agilord/aws_client#165]
As good as the DynamoDB api works now, it's not very ergonomic. The JS SDK has what is called a [DocumentClient](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/dynamodb-example-document-client.html) that eases use of DynamoDB.

It should be possible to write a similar package for Dart. Question is if it should be a separate package or incorporated in the generated package.

@isoos WDYT?

**Comment by isoos** [comment]
There seem to be pros and cons for both ways, and I have no strong opinion on it. Let's do whatever is more productive to get started, we can make both work (e.g. we can update the dependencies if needed).

**Comment by Schwusch** [comment]
I think the package is ready to publish now, wdyt @isoos ?

**Comment by isoos** [comment]
+1, go ahead and publish it!

**Comment by Schwusch** [comment]
Done :D
