### ISSUE TITLE
XML based packages are broken

### ISSUE THREAD

**Issue by Schwusch** [agilord/aws_client#169]
After the XML package was bumped in https://github.com/agilord/aws_client/pull/166/ `query`/`xml` packages broke. We either need to revert to <4.0.0 or update the usage.

**Comment by isoos** [comment]
What's the error / what did broke?

**Comment by Schwusch** [comment]
The error says [The method 'findElements' isn't defined for the class 'XmlElement'.](https://pub.dev/packages/aws_sns_api#-analysis-tab-). Seems the api has changed
