### ISSUE TITLE
AWS dynamodb Bug for ReturnConsumedCapacity

### ISSUE THREAD

**Issue by pY4x3g** [agilord/aws_client#175]
Hi,

thank you for your library. The aws_dynamodb_api is already working really fine.

I think I found a small bug, the ReturnConsumedCapacity is not working. When I use the option ```returnConsumedCapacity: ReturnConsumedCapacity.total``` for a query or an update operation (DynamoDB.updateItem/DynamoDB.query) I get the following errors.

for a query:
```
Unhandled exception:
Converting object to an encodable object failed: Instance of 'ReturnConsumedCapacity'
#0      _JsonStringifier.writeObject (dart:convert/json.dart:659:7)
#1      _JsonStringifier.writeMap (dart:convert/json.dart:740:7)
#2      _JsonStringifier.writeJsonValue (dart:convert/json.dart:695:21)
#3      _JsonStringifier.writeObject (dart:convert/json.dart:650:9)
#4      _JsonStringStringifier.printOn (dart:convert/json.dart:846:17)
#5      _JsonStringStringifier.stringify (dart:convert/json.dart:831:5)
#6      JsonEncoder.convert (dart:convert/json.dart:260:30)
#7      JsonCodec.encode (dart:convert/json.dart:168:45)
#8      JsonProtocol.send (package:shared_aws_api/src/protocol/json.dart:53:45)
#9      DynamoDB.query (package:aws_dynamodb_api/dynamodb-2012-08-10.dart:3006:42)
```
for an update:
```
Unhandled exception:
Converting object to an encodable object failed: Instance of 'ReturnConsumedCapacity'
#0      _JsonStringifier.writeObject (dart:convert/json.dart:659:7)
#1      _JsonStringifier.writeMap (dart:convert/json.dart:740:7)
#2      _JsonStringifier.writeJsonValue (dart:convert/json.dart:695:21)
#3      _JsonStringifier.writeObject (dart:convert/json.dart:650:9)
#4      _JsonStringStringifier.printOn (dart:convert/json.dart:846:17)
#5      _JsonStringStringifier.stringify (dart:convert/json.dart:831:5)
#6      JsonEncoder.convert (dart:convert/json.dart:260:30)
#7      JsonCodec.encode (dart:convert/json.dart:168:45)
#8      JsonProtocol.send (package:shared_aws_api/src/protocol/json.dart:53:45)
#9      DynamoDB.updateItem (package:aws_dynamodb_api/dynamodb-2012-08-10.dart:4679:42)
```

**Comment by isoos** [comment]
@pY4x3g: thanks for reporting this

@Schwusch: I believe the issue is that the `payload` receives the `ReturnConsumedCapacity` enum unencoded, and `json.encode` has no idea how to serialize it. We'd need to encode it manually, or create a json-serialized payload object for each request.

**Comment by Schwusch** [comment]
Ah, this is a shame. Enums that are fields in serialized classes is behaving correctly, because `json_serializable` handles code like this:

```dart
enum AttributeAction {
  @_s.JsonValue('ADD')
  add,
  @_s.JsonValue('PUT')
  put,
  @_s.JsonValue('DELETE')
  delete,
}
```

The generated serialization code for `AttributeAction` is:
```dart
const _$AttributeActionEnumMap = {
  AttributeAction.add: 'ADD',
  AttributeAction.put: 'PUT',
  AttributeAction.delete: 'DELETE',
};
```
Which is then used like so:
```dart
writeNotNull('Action', _$AttributeActionEnumMap[instance.action])
```

`ReturnConsumedCapacity` is an argument to a method, and is not handled by the serialization library. @isoos You are right that we need to serialize it in our generated method before passing it to the shared library. We've already sketched out some solutions based on extension methods before, I'll see if I can dig them up from the commit history.

**Comment by isoos** [comment]
@pY4x3g: I've published `aws_dynamodb_api 0.0.2`. Please upgrade your dependencies and try it out.

**Comment by pY4x3g** [comment]
@isoos it's now working fine, thank you very much for the fast fix :)

**Comment by isoos** [comment]
@pY4x3g: @Schwusch was the one who was able to fix it quickly :)

**Comment by pY4x3g** [comment]
ops, then thank you for the fast organisation and thanks to @Schwusch for the fast fix :)
