### ISSUE TITLE
DocumentClient update bug?

### ISSUE THREAD

**Issue by pY4x3g** [agilord/aws_client#192]
Now I get an error if I try to run the DocumentClient.update method.
Although I specified the keys I get the following error:

```
Unhandled exception:
Invalid argument(s) (key): Must not be null
#0      ArgumentError.checkNotNull (dart:core/errors.dart:196:27)
#1      DynamoDB.updateItem (package:aws_dynamodb_api/dynamodb-2012-08-10.dart:4660:19)
#2      DocumentClient.update (package:document_client/document_client.dart:398:31)
```

I guess something is wrong in line 399 of document_client.dart, since the transformation (key: key.fromJsonToAttributeValue()) is returning null...

**Comment by Schwusch** [comment]
Thanks for the finding :) I did a woopsie in the type translator...
I pushed a [new version with a fix](https://pub.dev/packages/document_client#-changelog-tab-).

**Comment by pY4x3g** [comment]
Thanks its working now.
