### ISSUE TITLE
[DocumentClient] How to add a List of Numbers (not a NumberSet)?

### ISSUE THREAD

**Issue by pY4x3g** [agilord/aws_client#194]
Hi,
how do I add a List of Numbers to the database? The translator is translating any number list to a NumberSet which is not ordered and completely random in the dynamodb (`translator.dart:19`). Maybe we should check if the value is already an AttributeValue and return it in this case in the `toAttributeValue` method? With this I could just create the AttributeValue with a value `l` of a list of AttributeValues with type number like
```dart
  List<AttributeValue> dataListToAdd = [];

  for (var myNumber in [1,2,3]) {
    dataListToAdd.add(AttributeValue(n: myNumber.toString()));
  }
  var myValue = AttributeValue(l: dataListToAdd);
```

This was how it works with the DynamoDB class before. But currently this will create a json object and this will store it as a Map.
But that's only my first idea, maybe there is something better. Because it seems a bit random if the library uses a list or a set but this makes a huge difference for the user of the library.

Edit: I tried the simple fix by adding
```dart
  } else if (value is AttributeValue) {
    return value;
  }
```
to the `toAttributeValue` method and it is working for me.

**Comment by pY4x3g** [comment]
If you like the workaround I can create a pull request, but maybe there is a better idea.

**Comment by Schwusch** [comment]
> If you like the workaround I can create a pull request

I think it's a good idea, please do!

**Comment by Schwusch** [comment]
I'll do a release in a couple of hours when I'm on a computer.

**Comment by Schwusch** [comment]
@pY4x3g 0.0.6 is released :)

**Comment by pY4x3g** [comment]
thanks :)
