### ISSUE TITLE
AWS Cognito implementation

### ISSUE THREAD

**Issue by mehmetkemalbayer** [agilord/aws_client#2]
Hi,
I want to implement JS SDK of AWS Cognito in Dart.
I have just started to learn Dart after getting started with Flutter.
So if you please help me to start then I think I can handle the rest.
Best.

**Comment by isoos** [comment]
@mehmetkemalbayer Do you want to start with the AWS Cogito API? I'd rather suggest to start with a smaller extension to the current implementation, because (a) I believe the current code could use some improvements, and (b) it would be easier for you to start on a bigger task after a few smaller ones.

**Comment by mehmetkemalbayer** [comment]
Hi @isoos, 
I'm open to your redirections. 
I'm now starting with first task.
Sorry for late response.

**Comment by isoos** [comment]
Well, I can think of two starting points: the first one is to double check the request signing above, if there is already a library out there that does it (e.g. `crypto` or `pointycastle`).

The second one is to look at the SQS API and see if you can add a new method or two e.g. listing queues.

**Comment by mehmetkemalbayer** [comment]
Hi @isoos ,
I analyzed js code and found cognito use unauthenticated service call.
You can check here: [https://github.com/aws-amplify/amplify-js/blob/master/packages/amazon-cognito-identity-js/src/Client.js](url)
to see if I missed something.
Now I start adding new methods to SQS API.

**Comment by Schwusch** [comment]
There is now generated packages for Cognito:
- [Amazon Cognito Identity](https://pub.dev/packages/aws_cognito_identity_api)
- [Amazon Cognito Identity Provider](https://pub.dev/packages/aws_cognito_idp_api)
