### ISSUE TITLE
[DocumentClient] put method does not handle null for 'expected' parameter

### ISSUE THREAD

**Issue by pY4x3g** [agilord/aws_client#212]
Hi,

I tried to use the put method with only ``tableName`` and ``item`` parameter and I get the following error:

```
NoSuchMethodError: The method 'map' was called on null.
Receiver: null
Tried calling: map<String, ExpectedAttributeValue>(Closure: (String, ExpectedAttributeValueDC) => MapEntry<String, ExpectedAttributeValue>)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      DocumentClient.put (package:document_client/document_client.dart:239:26)
#2      main (package:dart_lambdas/apigateway2.dart:33:12)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```
Seems that the value null is not handled for the ``expected`` value. Maybe there is only an ? missing in document_client.dart:239  ?

Edit: yes an ? solves the problem. Line 239 should be
```dart
expected: expected?.map((key, value) => MapEntry(
```

**Comment by Schwusch** [comment]
Hi! Thanks for the report.
If you want, make a pull request and I'll do a new release as soon as possible. 
A workaround is to give `expected` an empty map until the release is out.
Nice job with the fix!
