### ISSUE TITLE
version issue

### ISSUE THREAD

**Issue by whatamelon** [agilord/aws_client#225]
```
Because every version of flutter_test from sdk depends on xml 3.6.1 and shared_aws_api >=0.2.0 depends on xml ^4.2.0, flutter_test from sdk is incompatible with shared_aws_api >=0.2.0.

And because aws_sns_api >=0.1.0 <0.1.1 depends on shared_aws_api ^0.2.0, flutter_test from sdk is incompatible with aws_sns_api >=0.1.0 <0.1.1.

So, because fitchoo depends on both aws_sns_api 0.1.0 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because fitchoo depends on both aws_sns_api 0.1.0 and flutter_test any from sdk, version solving failed.)
```

every flutter_test depends on [xml 3.6.1], but this library depends on [xml 4.2.0].
So you can downgrade xml version on 3.6.1 or even less?

**Comment by Schwusch** [comment]
That is weird, I can't find `xml` as a dependency in the [Flutter Test pubspec](https://github.com/flutter/flutter/blob/master/packages/flutter_test/pubspec.yaml), and the dependencies there seems very up to date. Which version of Flutter do you use?

**Comment by whatamelon** [comment]
Hi @Schwusch, I'm using flutter 1.17 stable. 
I just delete flutter_test and install aws_sns_api.
I just got question, How can I use this library? 
I can't find any example codes. So its difficult to start coding.
It will be good if you make example codes.
Thankyou!

**Comment by isoos** [comment]
As this is not a Flutter project, we are not following the exact same dependency stack as Flutter SDK.  You can always override dependencies in you `pubspec.yaml`, and hope that it will work :) - it probably will.

```
dependency_overrides:
  xml: 3.6.1
```

**Comment by Schwusch** [comment]
> How can I use this library? I can't find any example codes

We autogenerate the 120+ packages, so it's hard for us to provide examples. Amazon does [provide examples](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/sns-examples.html) for the Javascript SDK, which is very similar to the Dart equivalent. 
For example, this Javascript example:
```js
var createTopicPromise = new AWS.SNS({apiVersion: '2010-03-31'}).createTopic({Name: "TOPIC_NAME"}).promise();
```
This would be written like this in Dart:
```dart
var createTopicResponse = await SNS().createTopic(name: 'TOPIC_NAME');
```
You can read the [documentation on Pub](https://pub.dev/documentation/aws_sns_api/latest/sns-2010-03-31/SNS-class.html) if you want to know more details.

**Comment by whatamelon** [comment]
@Schwusch, @isoos  Thanks all the kindness!
