### ISSUE TITLE
Explore the possibility to use dart-lang/code_builder

### ISSUE THREAD

**Issue by Schwusch** [agilord/aws_client#226]
I've totally missed that this package exists https://github.com/dart-lang/code_builder .
It might perhaps have a positive effect on code readability.
@isoos wdyt?

**Comment by isoos** [comment]
It would be worth to try it...

**Comment by Schwusch** [comment]
I dn't think anyone has the time or energy to rewrite the project :sweat:, so I think it's time to close this one.
