### ISSUE TITLE
[document_client] Listening to subscriptions

### ISSUE THREAD

**Issue by dariotrombello** [agilord/aws_client#243]
Is it planned to implement a feature to listen to updates in the database?

**Comment by Schwusch** [comment]
I can't find anything about subscriptions in the [original documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html).
Can you explain a little bit more in detail what it is you'd like to see?

**Comment by dariotrombello** [comment]
Seems that it only works with AppSync + DynamoDB. The NodeJS library also doesn't support it.

**Comment by Schwusch** [comment]
I still find the question interesting though! 
It is fully possible that a Dart package with those features is desirable.
DocumentClient is already a handwritten package that isn't generated from an API spec.
I have no knowledge of how it would be done though, perhaps someone with insight into how AppSync works could be the judge of how feasible it is to implement in Dart.
