### ISSUE TITLE
IAM api does not support regions

### ISSUE THREAD

**Issue by xvrh** [agilord/aws_client#244]
Hi, thank you for this awesome libraries :-)

The generated `IAM` api (`iam-2010-05-08.dart`) takes a region parameter and forwards it to the QueryProtocol to build the api endpoint.

From the AWS documentation (https://docs.aws.amazon.com/general/latest/gr/rande.html), the IAM API do not support region.

The IAM API fails with a `SocketException: Failed host lookup: 'iam.eu-west-1.amazonaws.com'` error

**Comment by xvrh** [comment]
It seems the rules used in the JS SDK are here: https://github.com/aws/aws-sdk-js/blob/master/lib/region_config_data.json

Specifically the pattern to use for iam is: 
```
"globalSSL": {
      "endpoint": "https://{service}.amazonaws.com",
      "globalEndpoint": true,
      "signingRegion": "us-east-1"
    },
```

**Comment by Schwusch** [comment]
> It seems the rules used in the JS SDK are here

Great find! Next problem is to incorporate this with the code generation.
First step is to extract the config file in the [download command](https://github.com/agilord/aws_client/blob/master/generator/lib/download_command.dart#L39-L67), then read it in the [generate command](https://github.com/agilord/aws_client/blob/master/generator/lib/generate_command.dart#L115).
I can't give any guarantees that I will be able to work on this in the near future, so pull requests are most welcome!

**Comment by xvrh** [comment]
Thanks for the pointers.
I'll try to open a pull request :-)
