### ISSUE TITLE
XML List are not extracted correctly

### ISSUE THREAD

**Issue by xvrh** [agilord/aws_client#245]
For instance, the generated code for `ListRolePoliciesResponse` in the `IAM` API looks like:

```dart
  factory ListRolePoliciesResponse.fromXml(_s.XmlElement elem) {
    return ListRolePoliciesResponse(
      policyNames: _s
          .extractXmlChild(elem, 'PolicyNames')
          ?.let((elem) => _s.extractXmlStringListValues(elem, 'PolicyNames')),
    );
  }
```
https://github.com/agilord/aws_client/blob/7d4c87c83fdcdab81db1f0a0be57a805efb684c4/generated/aws_iam_api/lib/iam-2010-05-08.dart#L14691

However the returned response of AWS is:
```xml
<ListRolePoliciesResult>
  <PolicyNames>
    <member>CloudWatchPolicy</member>
    <member>DynamoDBPolicy</member>
  </PolicyNames>
</ListRolePoliciesResult>
```

So it should use `member` instead of `PolicyNames` in the `extractXmlStringListValues` call.
Or `extractXmlStringListValues` should not take the tag name and return the content of every children...

**Comment by Schwusch** [comment]
The relevant code is located [here](https://github.com/agilord/aws_client/blob/master/generator/lib/builders/library_builder.dart#L425-L428).
It seems `memberElemName` should be conditional somehow. The answer to whether the name should be `member` or something else is probably in the API spec. I haven't looked in to it though.

**Comment by Schwusch** [comment]
I made a PR with the `member` theory. Although the smartest move would be to check how the `aws-sdk-js` library does it, I haven't had the time to analyze it yet.

**Comment by xvrh** [comment]
Thanks for working on this.
I think that this is what aws-sdk-js is doing: https://github.com/aws/aws-sdk-js/blob/master/lib/xml/node_parser.js#L100

To be able to be more confident for the fix of these kind of protocol mistake, I started to port the tests of the js sdk (test/fixtures/output).

You can see some of the progress here: https://github.com/xvrh/aws_client/commit/b18a39fdb5d95a4e5ba045557c9dc7b1cc25a882
It generates some deserialisation tests for the different protocols.

I plan to open a PR soon to discuss it further.

**Comment by Schwusch** [comment]
> You can see some of the progress here: xvrh@b18a39f

Oh man, that's a massive endeavor! I made a [simple attempt](https://github.com/agilord/aws_client/tree/master/shared_aws_api/test/protocol) but you seem to have something seriously valuable in the making.
I look forward to the PR!
