### ISSUE TITLE
Lambda.updateFunctionCode doesn't work with zipFile

### ISSUE THREAD

**Issue by xvrh** [agilord/aws_client#251]
The `zipFile` parameter should be encoded in base64 by the library but is not.
The `List<int>` is encoded as it in the json which is not recognised by the server.

https://github.com/agilord/aws_client/blob/d31356e0d7ba15a404a673fdf1e8563b8e9bda15/generated/aws_lambda_api/lib/lambda-2015-03-31.dart#L4096

**Comment by Schwusch** [comment]
Should be pretty easy to fix, throw in a [base64Encode](https://api.dart.dev/stable/2.10.2/dart-convert/base64Encode.html) prefix for those types [here](https://github.com/agilord/aws_client/blob/master/generator/lib/builders/protocols/rest_json_builder.dart#L46-L54).
