### ISSUE TITLE
Lambda.createFunction doesn't work if "publish" is not specified

### ISSUE THREAD

**Issue by xvrh** [agilord/aws_client#252]
The `publish` argument is optional. But if it is not provided, the library puts a `null` value in the request payload which results in a `500 InternalFailure` error.

I guess the generated code should build a map only with the arguments that are not null:
```dart
final $payload = <String, dynamic>{
      'Code': code,
      //...
      if (publish != null)
        'Publish': publish,
    };
```
Or filter it before the `jsonEncode`.

**Comment by Schwusch** [comment]
That seems easy to mitigate by adding `'}..removeWhere(
        (dynamic key, dynamic value) => key == null || value == null);` [instead of `'}'`](https://github.com/agilord/aws_client/blob/master/generator/lib/builders/protocols/rest_json_builder.dart#L55) when constructing the payload.
It's either or I guess.
