### ISSUE TITLE
Amazon SES SendRawEmail API,

### ISSUE THREAD

**Issue by biancashouse** [agilord/aws_client#264]
Wanting to send a PDF attachment using the Raw api...

**Comment by Schwusch** [comment]
I'm sorry, but the only guidance I can give you is the documentation for [SES V1 `sendRawEmail`](https://pub.dev/documentation/aws_ses_api/latest/email-2010-12-01/SES/sendRawEmail.html) and the [SES V2 `sendEmail`](https://pub.dev/documentation/aws_sesv2_api/latest/sesv2-2019-09-27/SESV2/sendEmail.html) methods.
If there is any bugs in the Dart API, please feel free to open a new issue describing what problems you are having.
