### ISSUE TITLE
[Test suite failures] Output complex Map values

### ISSUE THREAD

**Issue by xvrh** [agilord/aws_client#285]
One output test is still failing because we fail to decode `Map<String, DateTime>` with a custom timestamp format.

One of the solution is to create a custom `JsonConverter` for each timestampFormat and apply it to the properties that need it.

**Comment by Schwusch** [comment]
I just did some investigation around this, and it seems no services has maps of DateTimes, only that test.

**Comment by xvrh** [comment]
There are 2 json apis with `List<DateTime>` (QuickSight and ComputeOptimizer) that would fail currently like the Map.
The solution with the JsonConverter would fix both map and list. I think we should keep the test.

**Comment by Schwusch** [comment]
Should we create a test that actually tests the list case then?

**Comment by Schwusch** [comment]
I added a case for the datetime lists and a fix for that case in #291
