### ISSUE TITLE
DateTime from server doesn't always respect protocol format

### ISSUE THREAD

**Issue by xvrh** [agilord/aws_client#288]
I notice some `rest-json` protocol returns some DateTime encoded as iso8610. 
While this library try to interpret it as unixTimestamp 
https://github.com/agilord/aws_client/blob/e68105fae4527f0fe44487fcc18de48976b55648/generator/lib/builders/library_builder.dart#L254

I see that aws-js-sdk has a parse function that try to support every format:
https://github.com/aws/aws-sdk-js/blob/7d4dd548f74f739dbe0df1c4b9cd88454ce5d131/lib/util.js#L330

**Comment by Schwusch** [comment]
Do you know which `rest-json` services have this behaviour? I'm thinking we might have missed some property in the definitions, or we should at least investigate.

**Comment by xvrh** [comment]
I investigated this and have found the (nasty) bug. I'll open a pull request with the details soon.
