### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by Schwusch** [agilord/aws_client#292]
We will have to support null safety at some point, and this ticket is for tracking that work.

**Comment by Schwusch** [comment]
At the time of writing, `shared_aws_api` is listed as the 7:th most blocking package blocking null safety migration:
https://github.com/dart-lang/sdk/wiki/Null-safety-migration-status

**Comment by Schwusch** [comment]
As it stands, we have 3 dependencies that are not migrated:
- package:crypto - https://github.com/dart-lang/crypto/issues/105
- package:http - https://github.com/dart-lang/http/issues/501
- package:build_runner - https://github.com/dart-lang/build/issues/2920

It seems `package:http` is close to a migrated release, and `package:crypto` seems to be migrated but no release.
I don't think `package:build_runner` needs to be migrated though, since it only runs when generating code?

**Comment by IchordeDionysos** [comment]
@Schwusch looks like you are now unblocked and should be able to migrate to null safety :) 
Also you are now the 2nd most blocking package after `dio`

**Comment by pshichenko** [comment]
Any way I can help with this?

**Comment by Schwusch** [comment]
@psichenko There is a branch, `null_safety`, that you are welcome to fork and work on.
I currently have migrated the shared package, and there is some attempts to generate null safe code in the generator.
First step is to try to run the generator and observe the changes.
Feel free to ask questions on Gitter at dart-lang/server if you need quick answers.

**Comment by xvrh** [comment]
Hi Jonathan, if you are not working on it right now, I may give it a try starting from you branch.

**Comment by Schwusch** [comment]
I guess we can close this now as the null safe services has been published as 1.0.0 in #324 
Better late than never :sloth: :runner: 
Thanks everyone who helped, @xvrh in particular :heart: 
![itsdone](https://user-images.githubusercontent.com/8165610/146456272-3dce264f-e3a0-4548-a672-b26f1bf1dbf2.gif)
