### ISSUE TITLE
Proposal: drop json_serializable dependency

### ISSUE THREAD

**Issue by xvrh** [agilord/aws_client#293]
It seems we have all the code necessary to [encode](https://github.com/agilord/aws_client/blob/master/generator/lib/builders/builder_utils.dart#L26) and [decode](https://github.com/agilord/aws_client/blob/master/generator/lib/builders/builder_utils.dart#L7) `Shape` in json. We use this code to serialize/deserialize the root Input and Output shape of an Operation.

I did a quick experiment and was able to drop the json_serializable generator and replace the `fromJson` and `toJson` method with this implementation and all the tests still work. It is a 10 LoC change.

The advantages that I see:
- Faster code generation (no build_runner to start)
- Consolidate to a single implementation of json encoding
- Less code: all the JsonConverters can be deleted

This is just an idea. Let me know what you think.
 I may be missing something important to consider?

**Comment by Schwusch** [comment]
I'm not sure I fully understand. Could you give an example of what would be migrated from `json_serializable` to `encodeJsonCode`/`extractJsonCode`?

**Comment by xvrh** [comment]
Hi Jonathan,
Sorry for not being clear, I'll try to clarify :-)

This is more or less what we generate now in rest-json api:
```dart
class Api {
  Future<OutputShape> operation(Struct param1, SomeEnum param2) async {
    var response = await _protocol.send(body: {
      'param1': param1.toJson(),
      'param2': param2.toValue(),
    });
    return OutputShape({
      field: response.headers['param1'],
      field2: Struct.fromJson(response.body),
    });
  }
}

class Struct {
  String field1;
  SomeEnum field2;
  
  Struct();
  
  // Current: Delegate fromJson/toJson to json_serializable
  factory Struct.fromJson(json) => _$StructFromJson(json);
  Map toJson() => _$StructToJson(this);
}
```

### Proposal
Remove the json_serializable step and generate directly fromJson/toJson for the Structure shapes.
```dart
class Struct {
  String field1;
  SomeEnum field2;

  Struct();

  // Proposal: generate fromJson/toJson methods directly
  factory Struct.fromJson(json) {
    return Struct(
      field1: json['field1'],
      field2: json['field1'].toSomeEnum(),
    );
  }

  Map toJson() => {
        'field1': field1,
        'field2': field2.toValue(),
      };
}
```

### Reasoning
We already have all the code needed to generate those methods because we have to generate it in the operation method.

### Experiment
In `library_builder.dart`, replace:
```dart
      if (shape.generateFromJson) {
        writeln(
            '\n  factory $name.fromJson(Map<String, dynamic> json) => _\$${name}FromJson(json);');
      }
  // ....
      if (shape.generateToJson) {
        writeln('\n  Map<String, dynamic> toJson() => _\$${name}ToJson(this);');
      }
```

with
```dart
      if (shape.generateFromJson) {
        writeln('\n  factory $name.fromJson(Map<String, dynamic> json) {');
        writeln('return $name(');
        for (var member in shape.members.where((m) => m.isBody)) {
          writeln(
              "${member.fieldName}: ${extractJsonCode(member.shapeClass, "json['${member.locationName ?? member.name}']", member: member)},");
        }
        writeln(');');
        writeln('}');
      }
  //...

      if (shape.generateToJson) {
        writeln('\n  Map<String, dynamic> toJson() => {');
        for (var member in shape.members.where((m) => m.isBody)) {
          if (!member.isRequired) {
            writeln('if (${member.fieldName} != null)');
          }
          final encodeCode = encodeJsonCode(member.shapeClass, member.fieldName,
              member: member, maybeNull: member.isRequired);
          final location = member.locationName ??
              member.shapeClass.locationName ??
              member.name;
          writeln("'$location': $encodeCode,");
        }
        writeln('};');
      }
```
(the code will actually be shared between here and the generated operation in rest-json protocol)

**Comment by Schwusch** [comment]
I am a bit afraid to roll our own serialization code, but I think could be something to try after we migrate to null-safety if you want to :) 
I'd like to make one release after we've fixed the unit-tests and before we start with null safety.
Messing with serialization before the big release feels risky, don't you think?

**Comment by xvrh** [comment]
Sure! I understand that it's risky and we will need some time to test it.
I won't go ahead with that right now :-)

For the medium term though I think this is a really a GREAT opportunity to simplify the code generation (and speed it up).

**Comment by Schwusch** [comment]
Can we consider this done now?

**Comment by xvrh** [comment]
Yes if I remember well, it was done with null-safety (https://github.com/agilord/aws_client/pull/308)
