### ISSUE TITLE
Release time?

### ISSUE THREAD

**Issue by Schwusch** [agilord/aws_client#297]
Given all the fixes that has been done, is it time to make a new release of all the packages?
I will assume the flow to be something like:
1. Bump and release the `shared_aws_api` package at a version high enough that it won't accidentally be used by old packages.
2. Bump the `shared_aws_api` dependency version in the generated packages.
3. Bump the generated packages versions (not sure how much, is it prime for 1.0?).
4. Release the generated packages

I know services like S3 still isn't fixed, but it has been such a long time (and so many fixes!) since last release.
@isoos @xvrh What is your thoughts?

**Comment by xvrh** [comment]
+1 for a release!

Not sure it's really ready for 1.0. Like you said, there may still be some issues with signatures.

**Comment by Schwusch** [comment]
I might go ahead and do a release soon, we're getting issues such as #300, which we've fixed since last release.

**Comment by Schwusch** [comment]
All packages except `document_client` have been updated in #301 and published,
- shared_aws_api -> 0.3.0
- generated packages -> 0.2.0
