### ISSUE TITLE
Allow to close the internal http.Client

### ISSUE THREAD

**Issue by xvrh** [agilord/aws_client#302]
Each protocol creates a `http.Client` internally if none is provided in the service constructor.
But we don't expose this client and don't offer a way to close it.

When a client is not closed, the process hangs for several seconds until it timeouts.

So the correct way to use the API right now is to pass the client manually and close it.
```dart
  var client = Client();
  var api = Lambda(region: 'eu-west-1', client: client);
  try {
    //...
  } finally {
    client.close();
  }
```

We could improve the situation with either:
- Add a `close()` method on every services (it simplifies a bit the pattern above)
- If no client is provided, create a new client and close it for each request

**Comment by isoos** [comment]
Creating client for each request seems to be a waste of resources. At other places I've seen the following pattern:
- auto-create client in the constructor, close it in the `close()` method
- when a `client` is provided in the constructor, do not close it in `close()`

**Comment by Schwusch** [comment]
Is this still a problem? Should we address it?

**Comment by Schwusch** [comment]
In the new Kotlin AWS SDK, `close()` does what @isoos describes
