### ISSUE TITLE
Version issue  flutter 1.12.6 to 2.6.0 

### ISSUE THREAD

**Issue by MurtuzaSrashtaSoft** [agilord/aws_client#310]
we migrate out code flutter 1.12.6 to 2.6.0 but we have received the below error while pub get.

Because every version of flutter_localizations from sdk depends on intl 0.17.0 and shared_aws_api >=0.1.2 depends on intl ^0.16.1, flutter_localizations from sdk is incompatible with shared_aws_api >=0.1.2.
And because aws_dynamodb_api >=0.2.0 depends on shared_aws_api ^0.3.0, flutter_localizations from sdk is incompatible with aws_dynamodb_api >=0.2.0.
So, because smart_home depends on both flutter_localizations any from sdk and aws_dynamodb_api ^0.2.0, version solving failed.
pub get failed (1; So, because smart_home depends on both flutter_localizations any from sdk and aws_dynamodb_api ^0.2.0, version solving failed.)

**Comment by Schwusch** [comment]
Hi @MurtuzaSrashtaSoft !
Does updating `aws_dynamodb_api` to version 1.0.0 solve your problem?

**Comment by Schwusch** [comment]
I'll consider this to be solved.
If there is any problems with the null safe versions, feel free to open a new issue.
