### ISSUE TITLE
N U L L  S A F E T Y  ;-)

### ISSUE THREAD

**Issue by biancashouse** [agilord/aws_client#311]
Pretty Please. Pls don't make me go back to f***base !

**Comment by saharvx9** [comment]
PLS SUPPORT IT!!!

**Comment by xvrh** [comment]
Null safety is merged on master in this repository. It is not published on pub.dev yet, so you have to depends on this package with git dependencies in your pubspec.yaml.

**Comment by Schwusch** [comment]
Perhaps it would be useful to make a prerelease on pub.dev? Would be good to get some testing from folks that don't want to have a git dependency.

**Comment by BlackStriker99** [comment]
Hello @xvrh, I Have tried using git repo  dependency but it is giving me error pubspec.yaml missing.

![Screenshot from 2021-08-12 12-41-14](https://user-images.githubusercontent.com/40071991/129153594-ff77fdd4-45a6-40b2-a742-7d2d2f364911.png)

My Pubspec.yaml file is like this

![Screenshot from 2021-08-12 12-48-17](https://user-images.githubusercontent.com/40071991/129154509-ad97874f-09cb-4308-ab28-14833cf0766e.png)

Can you please help me out what will be the proper way to use this repo with git dependency.

**Comment by isoos** [comment]
@BlackStriker99: Follow the last example in the pubspec documentation:
https://dart.dev/tools/pub/dependencies#git-packages

There is a `path` property which you can use to specify a directory inside the repository.

**Comment by BlackStriker99** [comment]
Thanks for quick reply @isoos i have already tried that and i always get same error

when i tried with git@github.com: (SSH)

![Screenshot from 2021-08-12 13-13-46](https://user-images.githubusercontent.com/40071991/129157956-0bb1f124-af27-4e9d-8ce7-2466fa43ecc1.png)

I got 

![Screenshot from 2021-08-12 13-15-52](https://user-images.githubusercontent.com/40071991/129158296-1c0a3994-e4e2-4e5c-bc52-4f341874e538.png)

and i have also tried with  https://

![Screenshot from 2021-08-12 13-17-13](https://user-images.githubusercontent.com/40071991/129158547-2434d410-61ec-4ffc-82b3-2edf4849694f.png)

in that i got same error

![Screenshot from 2021-08-12 13-18-25](https://user-images.githubusercontent.com/40071991/129158721-3a457d59-49af-4d4f-bb35-c815f2bcd0c3.png)

Thanks in advance !!

**Comment by isoos** [comment]
You need to use `path: generated/aws_dynamodb_api`

**Comment by BlackStriker99** [comment]
**Thanks !!** @isoos i was able to get this package from git repo

**Comment by ryanheise** [comment]
> You need to use `path: generated/aws_dynamodb_api`

Although note that even this version in Git still has an outdated dependency on the hosted, _non-nullsafe_ version of shared_aws_api, so if you want to run it with the correct dependency, you'll need to fix it with a dependency override:

```yaml
dependency_overrides:
  shared_aws_api:
    git:
      url: git@github.com:agilord/aws_client.git
      path: shared_aws_api
```

**Comment by Schwusch** [comment]
All packages are now updated to null safety at version 1.0.0.
Please open another issue if there is any problems with those versions.
