### ISSUE TITLE
How do we use it to stream videos to Kinesis stream?

### ISSUE THREAD

**Issue by logblythe** [agilord/aws_client#315]

**Comment by satyajitghana** [comment]
+1 on this, i've been searching for a solution for weeks, havn't found any.

One way is to use Android Producer library and use Dart to call that, but that defeats the purpose of having flutter libraries of aws.

**Comment by satyajitghana** [comment]
@logblythe found anything?

**Comment by Schwusch** [comment]
This is the same discussion as in #242. This SDK does not the include the Kinesis producer capability.
