### ISSUE TITLE
Design / feature: Unsigned requests and temporary credentials

### ISSUE THREAD

**Issue by simonbuchan** [agilord/aws_client#316]
First off, thanks for your work so far on this!

I'm looking at using our current services from Flutter, and I've got two issues so far, both of which are pretty closely related and have a decent, but potentially API breaking, fix.

First I would like to be able to use the generated cognito-idp clients for the *non* admin APIs, that is, sign in, confirm codes, etc. as the existing official amplify APIs are awful and confusing and incompatible with this SDK, but I've got the relevant bits needed for the SRP login factored out into a library that sits on top of just `http.Client` so far - but the types / error handling mismatch kind of sucks. Unfortunately, the current design doesn't support *unsigned* service requests, or not providing *any* credentials (not just letting the service default to `AwsClientCredentials.resolve()`). This is described by the JS SDK api models with `"authtype": "none"` on the `"operations"` item, so it should be pretty easy after allowing not having credentials.

Second, the `cognito-identity` service (and others) can hand out temporary credentials, which the `AwsClientCredentials` class doesn't currently handle. The JS SDK handles this differently between v2 and v3: in v2, the `Credentials` base type has a virtual `get()` that derived types can override to update - if needed - the `accessKeyId` etc. properties which must be called before any signing, while in v3, all credentials parameters to the service are simply replaced with a credentials provider function.

If you like, I could take a stab at a PR that supports these? Any feedback or preferences would be welcome.

**Comment by simonbuchan** [comment]
As an example, my preference for implementing this would look something like:

```dart
// basically like before:
class FooService {
  final AwsClientCredentials credentials;

  FooService({
    ...
    this.credentials = AwsClientCredentials.default,
  });
}

// but now:

class AwsClientCredentials {
  // no fields! would require client changes if they were accessing these, but a relatively straightforward fix and makes their code more likely to be correct.

  // default / compatibility is static credentials
  factory AwsClientCredentials({ String accessKeyId, ... }) => StaticAwsClientCredentials({ accessKeyId: accessKeyId, ... });

  // the default provider fallback chain. Since this class is now immutable, and resolution is deferred, this can be a shared static.
  static AwsClientCredentials default = DefaultAwsClientCredentials();

  // all the specific providers...
  factory AwsClientCredentials.ec2() => ...

  // Actually resolves the current values, including refreshing from the external source if needed.
  // Resolves to null if it's AwsClientCredentials.none()
  abstract Future<StaticAwsClientCredentials?> values();
}
```

**Comment by Schwusch** [comment]
Was this solved when merging #318?

**Comment by simonbuchan** [comment]
Good question! I think, technically the first part is, in that you can pass invalid credentials that will be ignored for service actions that don't expect authentication, but I believe you can make unauthenticated requests otherwise if IAM grants public access, and overall it's really a clumsy hack rather than a deliberate API.

Really the issue is that second part about temporary credentials, (which you absolutely should be using for any client side code if you can), and which currently are clumsy to use: you basically have to wrap up any access to your client instance with something that will fetch and cache the credentials, rebuild the service with the updated credentials and any other configuration. It's easy to get wrong too: clock skew, retries need to revalidate the credentials, and so on. There's a reason the official libraries all handle credential expiry. 

That design I sketched still looks basically fine for resolving this, but I haven't been doing any Flutter/Dart recently nor am I likely to in the near future. I didn't attempt the larger PR at the time as it really needed agreement from the project that it made sense to then before I spent the time, given what a wide impact it would have on the code.

**Comment by Schwusch** [comment]
I was annoyed the other day when I wanted to assume a role in order to access some resource, since we don't support resolving credentials through STS, as the JS SDK does.
We don't even support using a session token from the shared `~/.aws/credentials` file.
I think it would be a good idea to copy the "credential provider" approach you mentioned, which would offer more flexibility/extendability.
I am thinking about taking a stab at it, if you haven't already. I think it warrants breaking the API.

**Comment by Schwusch** [comment]
I started experimenting on this branch https://github.com/agilord/aws_client/tree/resolve_assumed_roles_credentials .
It's not a copy of how the JS SDK does it, but a least effort adjustment that enables my use case with the assumed role from STS.
Theoretically, all sorts of providers can be added I guess.

**Comment by Schwusch** [comment]
Generated services v1.1.0 now have the possibility to take an asynchronous `credentialsProvider`, which opens up use cases mentioned above. More work can be done to provide different ways to provide credentials out of the box, but at least it's more flexible at the moment.
