### ISSUE TITLE
Please update pub with nullsafety and latest pub

### ISSUE THREAD

**Issue by MurtuzaSrashtaSoft** [agilord/aws_client#319]
Please update the pub with null safety and the latest pub.

There are 3 new pull requests please do a moment on that.

**Comment by MurtuzaSrashtaSoft** [comment]
i m not able to update flutter SDK with the latest because this pub does not support for latest flutter SDK.

**Comment by Schwusch** [comment]
Hi @MurtuzaSrashtaSoft !
All packages has been updated to null safe 1.0.0 on pub, does that solve your problem?

**Comment by Schwusch** [comment]
I'll consider this to be solved.
If there is any problems with the null safe versions, feel free to open a new issue.
