### ISSUE TITLE
Is there any documentation?

### ISSUE THREAD

**Issue by wijesijp** [agilord/aws_client#320]
Can't find any documentation detailing how to integrate this package with flutter.

Can you please provide a link to some documentation showing how to use this with flutter?

**Comment by Scylla2020** [comment]
I found this helpful.

[https://github.com/agilord/aws_client/blob/master/aws_client/examples/lambda.example.dart](url)

**Comment by Scylla2020** [comment]
Bit of documentation here:

[https://pub.dev/documentation/aws_client/latest/index.html](url)

**Comment by Schwusch** [comment]
Every package has API documentation on Pub, e.g. https://pub.dev/documentation/aws_sns_api/latest/.
Regarding integration/usage, I recommend the [official AWS documentation for the JS SDKs.](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/sdk-code-samples.html) 
The usage is very similar.
If you have any other questions, feel free to open a new issue.
