### ISSUE TITLE
Not have MeetingSession on aws chime

### ISSUE THREAD

**Issue by machuytu** [agilord/aws_client#357]
Hey guys,
I want to use aws_chime_api package and when I try to create a meeting follow https://docs.aws.amazon.com/chime/latest/dg/create-mtgs.html I see it need config MeetingSessionConfiguration but when I call on package I not see it. So how can I get it?
![image](https://user-images.githubusercontent.com/50764579/159668189-11a61367-dbd5-47eb-b417-69624e5c171d.png)
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/50764579/159668359-2085e9ed-20b9-4761-a079-1bc00631a0ed.png">

**Comment by Schwusch** [comment]
This SDK does not contain a client library, you should take a look at [this list](https://docs.aws.amazon.com/chime/latest/dg/mtgs-sdk-client-lib.html) for more information.
There seems to be a Flutter client library [listed on Pub](https://pub.dev/packages/eggnstone_amazon_chime) as well.
