### ISSUE TITLE
An example of streaming data to amazon Personalize [QUESTION]

### ISSUE THREAD

**Issue by Nader2004** [agilord/aws_client#358]
Hello there. Thanks for the Amazon Personalize Package. May Anyone please provide a sample dart code that show streaming data such as users, items and events into datasets. I want to create real time recommendations. Thanks

**Comment by Schwusch** [comment]
Hi @Nader2004
This might not be the best forum to ask for example code. Examples and detailed API documentation is provided by AWS for their supported language SDKs, and the SDK that resembles the Dart SDK the most is [aws-sdk-js](https://github.com/aws/aws-sdk-js).
I would suggest forums like StackOverflow or the [Dart Server Gitter](https://gitter.im/dart-lang/server) for better responses.

Cheers
