### ISSUE TITLE
Upgrade to xml ^6

### ISSUE THREAD

**Issue by ryanheise** [agilord/aws_client#365]
The current dependency of ^5.0.2 needs to be bumped to ^6.0.0 to allow integration with the latest versions of other packages that depend on xml ^6.0.0.

**Comment by YonatanSegura97** [comment]
Any workaround meanwhile?

**Comment by isoos** [comment]
As a quick fix, I think `dependency_overrides` should work:
https://dart.dev/tools/pub/dependencies#dependency-overrides

**Comment by raphaelbarbosaqwerty** [comment]
workaround:

pubspec.yaml
``` yaml
dependency_overrides:
  xml:
```

Worked without any problem.

**Comment by Schwusch** [comment]
This is fixed as of #378 , update your aws packages to 2.0.0 and open a new issue if this doesn't work for you!
