### ISSUE TITLE
MalformedInput Sender: timestamp must follow ISO8601

### ISSUE THREAD

**Issue by cbatson** [agilord/aws_client#371]
When using [`CloudWatch.putMetricData()`](https://github.com/agilord/aws_client/blob/e25e160b4912af146d7ce173fcf186f0489ee5c7/generated/aws_cloudwatch_api/lib/monitoring-2010-08-01.dart#L2589), this error is observed:

```
MalformedInput Sender: timestamp must follow ISO8601
#0 QueryProtocol.send (package:shared_aws_api/src/protocol/query.dart:100:7)
<asynchronous suspension>
#1 CloudWatch.putMetricData (package:aws_cloudwatch_api/monitoring-2010-08-01.dart:2605:5)
<asynchronous suspension>
#2 FutureExtensions.onError.<anonymous closure> (dart:async/future.dart:1014:15)
<asynchronous suspension>
```

**Comment by cbatson** [comment]
> By running integration test with actual AWS Cloudwatch service, I found that Timestamp value should be formatted as ISO8601 rather than unix (epoc) millis.

[source](https://github.com/ex-aws/ex_aws_cloudwatch/issues/7#issuecomment-402256446)

**Comment by cbatson** [comment]
See also https://github.com/aws/aws-sdk-js/issues/1922

**Comment by cbatson** [comment]
Without diving deeper into how the [upstream JS SDK](https://github.com/aws/aws-sdk-js) parses API definitions, it's not clear to me how to resolve this. It seems like one of the following is needed:

1. an update to the upstream [API definition JSON](https://github.com/aws/aws-sdk-js/blob/ea3e23e01f875fd720611b82d8827184c15fc684/apis/monitoring-2010-08-01.normal.json) to explicitly state `timestampFormat` for this field
2. a more faithful conversion from the API definition to Dart (there is clearly some discrepancy since the JS SDK processes `putMetricData()` correctly)
3. a special case / workaround applied on the `aws_client` side

For reference, [here](https://github.com/agilord/aws_client/blob/e25e160b4912af146d7ce173fcf186f0489ee5c7/generator/lib/builders/builder_utils.dart#L120-L123) is where `aws_client` generator is emitting the faulty timestamp value.

A work-around is to manually edit the generated output [here](https://github.com/agilord/aws_client/blob/e25e160b4912af146d7ce173fcf186f0489ee5c7/generated/aws_cloudwatch_api/lib/monitoring-2010-08-01.dart#L4489) and change `unixTimestampToJson(timestamp)` to `iso8601ToJson(timestamp)`.

I did find [this](https://github.com/aws/aws-sdk-js/blob/ea3e23e01f875fd720611b82d8827184c15fc684/clients/cloudwatch.d.ts#L2164) which may explain why this works in the JS SDK.

**Comment by Schwusch** [comment]
I think it is okay to make a special workaround, i.e an `if (api == 'CloudWatch")` somehow. It seems to have passed a few years without any fixes upstream, so we can't expect the root cause to be fixed any time soon.

**Comment by xvrh** [comment]
By looking quickly at aws-js-sdk, it seems the default date format to use depends on the protocol:

https://github.com/aws/aws-sdk-js/blob/master/lib/model/shape.js#L292-L301

    switch (this.api.protocol) {
      case 'json':
      case 'rest-json':
        property(this, 'timestampFormat', 'unixTimestamp');
        break;
      case 'rest-xml':
      case 'query':
      case 'ec2':
        property(this, 'timestampFormat', 'iso8601');
        break;

**Comment by Schwusch** [comment]
Nice find @xvrh and @cbatson , not sure why we didn't use the existing `calculateDateTimeToJson` :shrug:
