### ISSUE TITLE
aws_sesv2_api still requires uuid v3.0.3 

### ISSUE THREAD

**Issue by mike-novarca** [agilord/aws_client#418]
aws_sesv2_api still requires uuid v3.0.3 
This is causing a conflict with more modern packages

**Comment by isoos** [comment]
@mike-novarca: I think you may just override the dependency in your pubspec:
https://dart.dev/tools/pub/dependencies#dependency-overrides

In the past months we have gone back to only use `package:aws_client` as a giga-API-client package, and we should deprecate the individual packages that are still using the separate ones.

**Comment by isoos** [comment]
(Note: I think I'll write a script, this should be automated :) )
