### ISSUE TITLE
Please Release [PR](https://github.com/agilord/aws_client/pull/414)

### ISSUE THREAD

**Issue by Jaew00Shin** [agilord/aws_client#422]
<img width="661" alt="스크린샷 2024-05-14 오후 3 16 58" src="https://github.com/agilord/aws_client/assets/69617087/81a11454-e200-4d8c-930e-086ecdd4f31c">

I cannot use intl 1.19.0

Please release this pull request for me to use intl 1.19.0

https://github.com/agilord/aws_client/pull/414

**Comment by AlienKevin** [comment]
Same request. Would be great if a new release with updated dependencies can be made. The latest Flutter version 3.22.0 requires intl 1.19.0, which makes things quite inconvenient.

**Comment by isoos** [comment]
Published.

Please note: you can always override your dependencies in you app using dependency overrides: https://dart.dev/tools/pub/dependencies#dependency-overrides
