### ISSUE TITLE
Add support for Bedrock Runtime API

### ISSUE THREAD

**Issue by davidmigloz** [agilord/aws_client#423]
Hi there!

First of all, thanks for your work, the project looks great.

I'm the maintainer of [LangChain.dart](https://github.com/davidmigloz/langchain_dart) and I've been researching how to integrate AWS Bedrock to support running inference on the models it supports.

Currently, there isn't a Dart AWS Bedrock client that I know of. But given the infrastructure you've developed, I think it will be fairly straightforward to add support for it to your project.

AWS Bedrock has 4 APIs:
- [bedrock](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/bedrock)
- [bedrock-agent](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/bedrock-agent)
- [bedrock-agent-runtime](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/bedrock-agent-runtime)
- [bedrock-runtime](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/bedrock-runtime)

In my case, I'm only interested in the Bedrock runtime, which is the one that allows you to run inference on the models.

Let me know if it's doable and how I can help with the implementation.

**Comment by isoos** [comment]
Since we are fetching the API definitions from this AWS repository, and it seems that the bedrock APIs are already there, I think it is mostly re-running the generator and publishing a new version, with a lot of finger crossing :)
https://github.com/aws/aws-sdk-js/tree/master/apis

I haven't done it for a while, but if nobody else picks it up, I shall find some time for it later this week.

**Comment by isoos** [comment]
Apparently it is more than just running the generator: the API definitions were expanded, there are new fields that may or may not be processed (I haven't reviewed them yet, just found out that we need to do more than a version upgrade).

**Comment by davidmigloz** [comment]
oh wow that was quick, thanks!!
I'll give it a try 🙂
