### ISSUE TITLE
Failed host lookup: 's3..amazonaws.com' 

### ISSUE THREAD

**Issue by Illia-Dulebov** [agilord/aws_client#433]
Unhandled Exception: ClientException with SocketException: Failed host lookup: 's3..amazonaws.com' (OS Error: No address associated with hostname, errno = 7)

got this using 

final output = await amazonApi?.putObject(
        bucket: "example",
        //bucketKeyEnabled: true,
        key: "files/$keyFilePath",
        body: File(filePath).readAsBytesSync());
        
How to fix it?

**Comment by isoos** [comment]
I think this may be the double dot between `s3` and `amazonaws.com`. Remove one of the dots?

**Comment by Illia-Dulebov** [comment]
I used this package to upload, it worked fine until i got this, is where any way to set the url request?
