### ISSUE TITLE
One package vs. multiple packages for generated code.

### ISSUE THREAD

**Issue by isoos** [agilord/aws_client#63]
/cc @Schwusch 

The current `aws_client/lib/generated` directory is 28MB. `package:googleapis` is a similar package, it is generated from service definitions, and it already had issues on pub.dev with dartdoc-generation or analysis timing out.

Should we aim for N smaller packages instead of one big "everything-in-it" package?

**Comment by Schwusch** [comment]
That will be a lot of packages... Java SDK does it that way I think. Should the generator generate packages then? Is that possible?

**Comment by isoos** [comment]
Yeah, we have 219 directories under `lib/generated/`. It is a lot, but packages could be generated the same way as these libraries themselves (they need at minimum a `pubspec.yaml` and their own subdirectory). Not really nice, but versioning and publishing could be scripted too.

As a maintainer, I'd probably prefer the single one, but as a user I'd probably be happier with smaller, specialized packages.

**Comment by Schwusch** [comment]
Would we make someone irritated if we published 219 packages? What is being said in the googleapis discussions?

**Comment by isoos** [comment]
Roughly these are the things we need to consider:
- A single large all-in-one package can collect popularity and likes easier.
- A single large all-in-one package will take forever (*) to analyze and generate dartdoc for it. (*) The current pub.dev limit is 10 minutes for dartdoc, I've aborted it on my local machine after 25 minutes.
- I've asked around, and on pub.dev there is no worry about an extra 200+ packages.
- It will be harder to meaningfully track the versions and the changelogs if we go the multi-package route. Even the package naming becomes problematic.

For me the likes and the popularity score is secondary, I'd rather have a correct analysis and API docs generated, which would point to the multi-package solution. @Schwusch wdyt?

**Comment by Schwusch** [comment]
Tell me if this is a crazy idea: can we have 220 packages, where one is a cumulative package, basically depending on 219 packages and re-exporting them. The analyzing would be distributed then, no? How would dartdoc behave?

**Comment by isoos** [comment]
Unfortunately it doesn't help the dartdoc API generation, and I doubt that it helps the analysis.

Another aspect: would you like to import the 2-3 libraries you are using, or do you want to have 1, but 97% of them may not be used at all (and potentially increases compile / startup times).

**Comment by Schwusch** [comment]
If I have understood the JIT-compiler correctly, it won't tree-shake what so ever. That means, that if you import `aws_client` which exports 219 services and all versions of those, everything will be included in the build. 

My gut feeling says that 219 packages will be more appreciated. We can experiment afterwards with a cumulative package, no? It feels weird to me that dartdocs and the analyzer would be bogged down with transitive dependencies.

**Comment by isoos** [comment]
> My gut feeling says that 219 packages will be more appreciated. We can experiment afterwards with a cumulative package, no?

+1

> It feels weird to me that dartdocs and the analyzer would be bogged down with transitive dependencies.

From the public surface point of view, if you export a class (or a full library), it becomes the part of your current library. For the clients these classes are in that library, and they are analyzed and documented as such.

**Comment by Schwusch** [comment]
If we go the multiple package route, and succeed to sanitize the documentation provided in the JSON somehow (god help us), the packages will be very well documented! A file can be +10k LOC with all the potential documentation there is...

**Comment by isoos** [comment]
Ok, I'll create the multi-package setup then. With that, I think it may be time to add the generated files to the git repository for reference, and also to track the changes of the codegen on each PR.

**Comment by Schwusch** [comment]
That's probably a good idea. I am unsure if the `json_serializer`-generated code should be submitted though. 

Do you have any thoughts on the shared dependencies? Have them as a separate package which the generated packages depend on?

**Comment by Schwusch** [comment]
I feel like this is resolved. We generate multiple packages, and it is unlikely to change.
