### ISSUE TITLE
Sqs create queue and STS Credentials

### ISSUE THREAD

**Issue by ipconfiger** [agilord/aws_client#7]
I want to use this lib in Flutter, so i have to implement STS Credentials. And i need create queue API

**Comment by isoos** [comment]
I'll review and accept PRs, but I don't have time for this at the moment.

**Comment by ipconfiger** [comment]
I read the code and found sts was already implemented in master branch, so just add Sqs create queue  API. I will post the PRs later.

**Comment by Schwusch** [comment]
@isoos This should be solved now with:
 - https://pub.dev/packages/aws_sqs_api
 - https://pub.dev/packages/aws_sts_api
