### ISSUE TITLE
AWS dynamoDB

### ISSUE THREAD

**Issue by sspogra** [agilord/aws_client#83]
Can I use it for aws dynamoDB?

**Comment by isoos** [comment]
@sspogra: not at the moment, but we do have API definitions for DynamoDB and we are working to generate code that will use the protocol required for DynamoDB.

**Comment by Schwusch** [comment]
The work done so far on DynamoDB is in this folder: https://github.com/agilord/aws_client/tree/master/generated/aws_dynamodb_api

The shared library does not have a working `json`-protocol implementation yet, so it is not usable right now.

**Comment by wajeehulhassanvii** [comment]
Hi @Schwusch is the feature implemented now?

**Comment by Schwusch** [comment]
I am troubleshooting some request-signing bugs, but otherwise it is coming along.
It is not done yet though.
I might have to write a Signature Version 4 implementation since I haven't found one that works for the JSON protocol.

**Comment by Schwusch** [comment]
@wajeehulhassanvii You are welcome to try the generated package:
https://pub.dev/packages/aws_dynamodb_api

**Comment by salvatore373** [comment]
Hi everybody! Is the `aws_dynamodb_api` plugin stable now?

**Comment by Schwusch** [comment]
Hi @salvatore373!
I've tested some use cases myself, which work fine. We had a bug report https://github.com/agilord/aws_client/issues/175#issuecomment-632599720, and it seems to work for that user now. We are going to release a new version soon with a fix as mentioned here https://github.com/agilord/aws_client/pull/183#issue-422316738. It only affects you if you use binary sets though.
I just made a pull request #185 for our `DocumentClient` , which might aid the usage of DynamoDB as well.

With that all said, it's quite new and we haven't received a lot of feedback yet, so we are still at version `0.0.2`, which indicates that we don't know how the future looks.

We would be very glad if you tried it out and gave us your opinion!

**Comment by salvatore373** [comment]
Thank you for your response, @Schwusch . I will make my tests and I will inform you of the errors I find.

**Comment by salvatore373** [comment]
Is there an example I can follow to implement this plugin in my app?

**Comment by Schwusch** [comment]
@salvatore373 That depends on the use case, the package has a very similar api to the javascript version, so I would recommend checking out the [javascript examples](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/dynamodb-examples.html).
Or is your question specific to the Dart implementation?

**Comment by pY4x3g** [comment]
Hi @salvatore373, I'm using the library now without any erros. Here is a small example I just wrote (can be used freely). I had also some issues in starting to use this library, maybe this code snipped can be used for a starting example for the library.
The library can easily be used with the documentations provided by amazon for the aws client examples and the parameters correspond to very similar attributes.

```dart
import 'dart:convert';
import 'dart:io';
import 'dart:math';

import 'package:aws_dynamodb_api/dynamodb-2012-08-10.dart';

final String region = "eu-central-1";

bool local;
AwsClientCredentials cred;

// WARNING, this example will assume that you have a table with the name 'test'
// in the region provided in the region String above.
// This script will modify and delete some data in the 'test' table
// and should be used with caution.


void main(List<String> arguments) async {
  final environment = Platform.environment;
  local = !environment.containsKey('AWS_ACCESS_KEY_ID');

  // check if the code is running inside a lambda function
  // it uses the credentials form the lambda environment if possible
  // otherwise it reads the accessKey and secretKey from the cred.json file
  if (local) {
    dynamic readAsString =
        jsonDecode(await new File('cred.json').readAsString());
    var accessKey = readAsString['accessKey'];
    var secretKey = readAsString['secretKey'];
    cred = AwsClientCredentials(accessKey: accessKey, secretKey: secretKey);
  } else {
    cred = AwsClientCredentials(
        accessKey: environment['AWS_ACCESS_KEY_ID'],
        secretKey: environment['AWS_SECRET_ACCESS_KEY'],
        sessionToken: environment['AWS_SESSION_TOKEN']);
  }

  //creating the dynamodb service
  final service = DynamoDB(region: region, credentials: cred);

  //creating list [0,1,2,3,4] to add to db (not neccesary for a set)
  List<AttributeValue> valuesList = [];
  for (int i = 0; i < 5; i++) {
    valuesList.add(AttributeValue(n: i.toString()));
  }

  var testAttribut = "test12345";

  //example update with catching ProvisionedThroughputExceededException
  // put operation will fail on ProvisionedThroughputExceededException
  // and has to be retried manually with own code logic
  try {
    var updateItemOutput = await service.putItem(
        tableName: "test",
        item: {
          "id": AttributeValue(s: randomString(12)),
          "ttl": AttributeValue(
              n: ((DateTime.now().millisecondsSinceEpoch / 1000).round() +
                      60 * 60 * 24 * 5)
                  .toString()),
          "testAttribut": AttributeValue(s: testAttribut),
          "data": AttributeValue(l: valuesList)
        },
        returnConsumedCapacity: ReturnConsumedCapacity.total);
  } on ProvisionedThroughputExceededException catch (e) {
    print('$e');
  }

  var myId = randomString(12);

  //example update
  var updateItemOutput = await service.updateItem(
      tableName: "test",
      returnConsumedCapacity: ReturnConsumedCapacity.total,
      key: {"id": AttributeValue(s: myId)},
      updateExpression: "set testString = :nd, #ttl = :t",
      expressionAttributeValues: {
        ":nd": AttributeValue(s: "myTestStringValue"),
        ":t": AttributeValue(
            n: ((DateTime.now().millisecondsSinceEpoch / 1000).round() +
                    60 * 60 * 24 * 7)
                .toString()),
      },
      expressionAttributeNames: {"#ttl": "ttl"});

  //example query
  QueryOutput o = await service.query(
      returnConsumedCapacity: ReturnConsumedCapacity.total,
      tableName: "test",
      keyConditionExpression: "id = :m",
      expressionAttributeValues: {":m": AttributeValue(s: myId)});
  print(
      "used: ${o.consumedCapacity.capacityUnits} readunits for ${o.count} items");
  for (var item in o.items) {
    print(item['testString'].s);
  }

  //example scan and removing all entries searching by field 'id'
  var scan = await service.scan(tableName: "test", limit: 2);
  for (var i in scan.items) {
    var deleteItemOutput =
        await service.deleteItem(key: {"id": i['id']}, tableName: "test");
    print('deleted one item');
  }
}

Random random = Random.secure();
const chars = "abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";

String randomString(int strlen) {
  String result = "";
  for (var i = 0; i < strlen; i++) {
    result += chars[random.nextInt(chars.length)];
  }
  return result;
}
```

**Comment by salvatore373** [comment]
Thank you @pY4x3g , that's exactly what I was talking about. I will try your code and I will inform you if I get some problems understading it.

**Comment by Schwusch** [comment]
To add on @pY4x3g s example, this is not required anymore:
```dart
cred = AwsClientCredentials(
        accessKey: environment['AWS_ACCESS_KEY_ID'],
        secretKey: environment['AWS_SECRET_ACCESS_KEY'],
        sessionToken: environment['AWS_SESSION_TOKEN']);
```

if the credentials exist as environment variables, they will be picked up and used. If they are not present, the library will look in the `$HOME/.aws/credentials` file like [described here](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/setup-credentials.html)

**Comment by pY4x3g** [comment]
@Schwusch, ah I didn't know about that, thank you for the update :)

**Comment by salvatore373** [comment]
@pY4x3g How do you use the `getItem()` method? I can't understand how to point to the node of the table I need using the `Key` object.

**Comment by pY4x3g** [comment]
@salvatore373 it strongly depends on how your primary index is structured, if you are using a single field as primary key you can just use
```dart
    var item = await service.getItem(key: {
      "id": AttributeValue(s: "myId")
    }, tableName: "test");
```
if you have a key with a search index you have to use both keys to get an item, ie
```dart
    var item = await service.getItem(key: {
      "id": AttributeValue(s: "myId"),
      "searchkey": AttributeValue(s: "myId2")
    }, tableName: "test");
```
If you don't know the sorting attribute you have to use a query. Also in the case if you use a secondary index I think you have to use a query against that index.

**Comment by salvatore373** [comment]
@pY4x3g Thank you very much for your help. I think I was getting in troubles because I was using a wrong structure of the DynamoDB. I am very new to DynamoDB, I come from Firebase RealTime Database.

**Comment by Schwusch** [comment]
If you are interested, I've published [document_client](https://pub.dev/packages/document_client), which is supposed to [simplify DynamoDB usage](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/dynamodb-example-document-client.html).

**Comment by salvatore373** [comment]
Hi everybody! How can I get an item of database saved as `Map`? And how can I put a `Map` inside an element of the database?

**Comment by pY4x3g** [comment]
@Schwusch thank you for the simplified library, just a small bug I found while trying this new library. Currently one can not have aws_client and the document_client in the same project because on the not compatible dependencies on xml, the error is as follows
```
Because no versions of document_client match >0.0.3 <0.1.0 and document_client 0.0.3 depends on shared_aws_api ^0.1.8, document_client ^0.0.3 requires shared_aws_api ^0.1.8.
And because no versions of shared_aws_api match >0.1.8 <0.2.0, document_client ^0.0.3 requires shared_aws_api 0.1.8.
And because shared_aws_api 0.1.8 depends on xml ^4.1.0 and aws_client >=0.1.2 depends on xml ^3.0.0, document_client ^0.0.3 is incompatible with aws_client >=0.1.2.
So, because dart_lambdas depends on both aws_client ^0.2.0 and document_client ^0.0.3, version solving failed.
```
As I remember correctly the ^ in front of the version does not allow a version change of the first digit since it normally indicates breaking changes.

**Comment by Schwusch** [comment]
@pY4x3g I'm curious, what do you use `aws_client` for? It hasn't been actively worked on, and there's generated packages with the same functionality now except `lambda`:
- [SNS](https://pub.dev/packages/aws_sns_api)
- [SQS](https://pub.dev/packages/aws_sqs_api)

**Comment by pY4x3g** [comment]
Ah yes I see, there where just some imports left I forgot to remove. I still thought that I have to include the aws_client package, but you are right. Thanks.
