### ISSUE TITLE
Make a new package named 'core' for shared code

### ISSUE THREAD

**Issue by Schwusch** [agilord/aws_client#95]
I think it is time to break with the old `aws_client` package, and put shared code for generated packages in a new package named `core`. It is a bit messy, and does not make semantic sense to  use the old package.

It will probably make users confused as well, to "reuse" the `aws_client` package in this way. Versioning would probably also be easier since we're starting at zero with a new package.

**Comment by isoos** [comment]
How about `shared_aws_api` ?

**Comment by Schwusch** [comment]
Yeah, the point would just be to separate this new thing from the old.

**Comment by Schwusch** [comment]
If we are to separate the shared dependencies, the `aws_client` concept doesn't feel relevant.
The `aws_client` prefix in this context for example:
```yaml
name: aws_client.generator
description: Code generator for package:aws_client
```
Since we're going with the multi-package route, and those packages does not have the prefix, that name will only be relevant within the original package.

**Comment by Schwusch** [comment]
This issue is arguably resolved with https://github.com/agilord/aws_client/pull/99. Should we close this?
